simplify find-and-replace script

diff --git a/bin/find-and-replace b/bin/find-and-replace
--- a/bin/find-and-replace
+++ b/bin/find-and-replace
@@ -1,4 +1,5 @@
-#!/bin/sh
+#!/usr/bin/env sh
+#
 # find-and-replace
 #
 # Find all occurances of a pattern within the current directory (recursively)
@@ -20,23 +21,19 @@
 # Tested on:
 # - Ubuntu 16.04
 
-# store command line arguments
-find=$1
-replace=$2
+# using unset variable causes error; exit script on error
+set -ue
 
-# print message
-echo "replace '$find' with '$replace'"
+main () (
+  find=$1
+  replace=$2
 
-# grep searches each file in ./ (current directory)
-# -r tells grep to search recursively (through sub directories)
-# -l tells grep to only output the names of the files that contain $find
-# | pipes grep's output (file names) into xargs
-# xargs uses these file names as extra command line parameters for sed
-# sed performs find and replace within each file
-# -e is followed by the find and replace expression
-# -i tells sed to perform the find and replace in-place, changing the files
-grep -rl "$find" ./ | xargs sed -e "s/$find/$replace/g" -i
+  echo "replace '$find' with '$replace'"
 
-# exit script gracefully
-exit 0
+  # recursively search each non-binary file in current directory for "$find"
+  # replace each occurence of "$find" with "$replace"
+  grep -Irl "$find" ./ | xargs sed "s/$find/$replace/g" --in-place
+)
+
+main "$@"
 
